export const PERFORM_FETCH_PRODUCT_LIST = 'PERFORM_FETCH_PRODUCT_LIST';
export const SUCCESS_FETCH_PRODUCT_LIST = 'SUCCESS_FETCH_PRODUCT_LIST';
export const ERROR_FETCH_PRODUCT_LIST = 'ERROR_FETCH_PRODUCT_LIST'; 
export const UPDATE_PRODUCT_QUA = 'UPDATE_PRODUCT_QUA';
export const CALCULATE_TOTAL_ORDER = 'CALCULATE_TOTAL_ORDER';
